TOTAL_NODES = 20
CLUSTER_SIZE = 5

SIMULATION_INTERVAL = 2

ENERGY_THRESHOLD = 20
PACKET_LOSS_THRESHOLD = 0.4

DRIFT_THRESHOLD = 6
OUTLIER_THRESHOLD = 12

NEIGHBOR_THRESHOLD = 8
HISTORY_THRESHOLD = 10
HISTORY_SIZE = 5

SENSORS = [
    "temperature",
    "humidity",
    "pressure",
    "light"
]